### ISSUE TITLE
Elaborate on running the Github Action intructions

### ISSUE THREAD

**Issue by Georgy5** [alterisian/helloworld#10]
## Issue observing Github Action run
Regards the instruction: 

> * observe Github Action run the script: ruby helloworld.rb

The way the Github Actions Workflow is setup (push or pull_requests on the "main" branch) I had to push to my fork in order to observe Github Action run the workflow.

## Goal
Make it clear if this is learning moment for the collaborator to figure out how to observe Github Action run,
OR write instructions on how the collaborator should do this, eg run Github Actions on their forked repo.

### Suggestion
Elaborate on the process instructions for running the Github Action workflow

**Comment by alterisian** [comment]
At this stage I cannot remember what we setup on Github actions. Lets figure it out in today's mob.

**Comment by Georgy5** [comment]
Adding `bundle exec` seems to have fixed the error
