### ISSUE TITLE
Geocoder Timeout

### ISSUE THREAD

**Issue by Georgy5** [alterisian/helloworld#23]
### This is not really an issue. Should we optimise for timeouts in our tests??

Today when running Rspec while my connection wasn't so good I got a timeout from geocoder.

The tests passed before and after, so it was due to my connection. Sharing this for "posterity" 😄

![geocoder_timeout](https://user-images.githubusercontent.com/2192560/226436620-2ec0bc40-f196-44f4-a377-6a2a8374dd8f.jpg)

**Comment by alterisian** [comment]
Use VCR? Mocking?

**Comment by alterisian** [comment]
Satisfied we close this now @Georgy5 ?
